version: "3"

services:
  db:
    build: ./database-service
    restart: always
    ports:
      - 3307:3306

  app:
    depends_on:
      - db
    build: .
    ports:
      - "8000:3000"
    environment:
      - DB_HOST=db
